Provided more informative error messages if git secrets not installed

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,4 +1,11 @@
 #!/usr/bin/env bash
+
+{ which git-secrets; } || {
+  echo 'git-secrets required and not found. See README for installation instructions.'
+  echo
+  exit 1
+}
+
 {
   git config --remove-section secrets 2>/dev/null
 } || {
